- hosts: all
  roles:
    - role: middleware_automation.redhat_csp_download.redhat_csp_download
      become: true
    - middleware_automation.wildfly.wildfly_install
    - middleware_automation.wildfly.wildfly_systemd